### ISSUE TITLE
Textuelle Suchen nach Studiengängen

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Studium#1]
Textuelle Suche soll in folgenden Feldern suchen:

- Titel
- Schlagworte/Interessen
- Studienart
- Beschreibung des Studiengangs

**Comment by xwolfde** [comment]
Kann erst mit dem Embed-Plugin getestet werden/Ausgabe ist Teil von diesem. Ggf. dahin schieben?

**Comment by xwolfde** [comment]
Umsetzung ok.
Aber nach Rollout beobachten, ob wir bei den Suchfeldern doch noch anpassen müssen.
