### ISSUE TITLE
Listenansicht bei allen Studiengängen - Spalten flexible ergänzen

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Studium#106]
für die englische Seite wäre es gut, wenn wir eine übersichtliche Liste der Studiengänge mit den Sprachvoraussetzungen haben. Am einfachsten wäre es vermutlich, hier bei der Listenansicht eine Spalte zu ergänzen mit den Inhalten des Feldes "Deutschkenntnisse für ausländische Studierende"

**Comment by xwolfde** [comment]
Dann definiere das doch mal, welcher Filter wie greifen soll. So ist das noch unklar...

Was haben wir an Feldern:
- Unterrichtssprache
- Sprachnachweise

Du willst also bei der SHortcode-Generierung eine Mehrfach-Option über diese beiden Felder. Das man dort entweder Alle (wie jetzt default) auswählt oder ein oder mehrere von den jeweiligen Feldern.

Oder? Erkläre es so, dass wir es als Auftrag geben und übersetzen können ;)

**Comment by wrcg** [comment]
neue Filteroption für "Sprachnachweise für internationale Studierende" bei den erweiterten Filtermöglichkeiten mit aufnehmen

**Comment by xwolfde** [comment]
Und WENN diese Option gesetzt wurde, DANN eine Spalte "Sprachnachweise" bei der Ausgabe der Listenansicht hinzufügen, welche dann in der Zeile dann jeweils den Inhalt zeigt.

**Comment by wrcg** [comment]
https://inpsyde.atlassian.net/jira/software/c/projects/FAU/issues/FAU-40

**Comment by wrcg** [comment]
ist umgesetzt
