### ISSUE TITLE
Button "Suche" muss optisch näher an Auswahlmöglichkeiten sein

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Studium#107]
evtl. Button Suche und Auswahlmöglichkeiten (Kachel/Liste) tauschen, um dem Nutzer zu verdeutlichen, dass die gewählte Auswahl bestätigt werden muss
optimal wäre, wenn ein Klick bei den Auswahlmöglichkeiten automatisch und ohne zusätzlichen Klick die Liste/Kacheln verändert

**Comment by wrcg** [comment]
![image](https://github.com/RRZE-Webteam/FAU-Studium/assets/9526974/f1f95655-a6dc-4161-8307-90e3997c4576)

**Comment by wrcg** [comment]
![image](https://github.com/RRZE-Webteam/FAU-Studium/assets/9526974/efe4f17a-6713-4f22-8113-3c2d81ca3a77)

**Comment by wrcg** [comment]
<img width="452" alt="image" src="https://github.com/RRZE-Webteam/FAU-Studium/assets/9526974/f98591c6-b5a4-4f7c-83a0-83c03e358e08">

**Comment by wrcg** [comment]
gerne dann eine andere Idee, aber die aktuelle Darstellung verwirrt sehr viele Nutzer

**Comment by xwolfde** [comment]
Würde ich nochmal gesondert mit unseren Designern besprechen wollen. Dann können wir daraus eikn konkreten Wireframe senden oder noch besser über ein Mergerequest zu https://github.com/RRZE-Webteam/FAU-Studium-Embed/blob/main/templates/search/search-filters.php einreichen.

Ich denke aber, wenn wir dei andere Sach emit der Suche verbessern, ist dies hier klarer.

**Comment by xwolfde** [comment]
Was du meinst ist auch "...bestätigen.." vielleicht was anderes? Nämlich die Bedienung der Selektoren und des Buttons, oder?

**Comment by xwolfde** [comment]
Wie besprochen hinfällig mit #108
