### ISSUE TITLE
Verbesserung der Suche: Klick-, Tab- und Touchverhalten

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Studium#108]
Aktuell ist es notwendig, den Suchknopf zu betätigen, damit die Suche startet.
DIes ist gerade bei der Nutzung von Maus auf Desktop unschön, da viele Nutzer hier erwarten, dass bereits bei dem betätigen eines Filters die Suche startet ohne dass noch extra auf "Suchen" geklickt werden muss.
Für Menschen, die aber nur die Tastatur zur EIngabe haben oder Leute, die via Touch arbeiten, ist es aber sehr wichtig, dass die Suche nicht unvermittelt startet, ohne dass diese es erforderten. 

Es sollte daher abhängig von der Zielgruppe ein anderes Verhalten des Suchknopfs herbei geführt werden:

1. Bei Usern, die Mouseclicks machen (onhover, onclick) wird die Auswahl eines Filters sofort zu einer Suche führen
2. Bei Usern mit Tastatur-Befehlen (onfocus , statt onhover), soll die RETURN-Taste oder wahlweise der Suchknopf die Suchaktion auslösen. Die SPACE-Taste verbleibt bei der Auswahl und dem Öffnen der Elemente/Selektoren, startet aber nicht die Suche.
3. Hinsichtlich Touch-Devices ggf. muss ggf. zwischen Handys in kleiner Auflösung und größeren Touch-Displays (IPad, Fernseher) unterschieden werden. Hierzu siehe Ansätze unten.

**Comment by wrcg** [comment]
bei Touch-Devices gibt es das Problem, dass man sich sehr schwer tut nach der Auswahl schnell genug auf den Suchbutton zu klicken. Suchbutton sollte dafür näher an den Auswahlfeldern sein. Oder könnte auch hier die Auswahl gleich zur Suche führen?

**Comment by wrcg** [comment]
für mobil/touch-device:
ähnlich wie hier: ![image](https://github.com/RRZE-Webteam/FAU-Studium/assets/9526974/4c9ce637-edf5-4da2-95fc-70c96a03cef0) nach jeder Filteroption ein "Suchen/Ergebnisse anzeigen"-Button 
...und die erweiterten Filter bei mobil nicht verstecken

**Comment by wrcg** [comment]
![image](https://github.com/RRZE-Webteam/FAU-Studium/assets/9526974/d89e7331-86fc-4075-ad92-3745f2775985)

Darstellung der Filter Fakultät, Beginn, Ort, etc. wie die oberen Filter - das "Verstecken" unter erweiterte Filter hat aus meiner Sicht hier keinen Mehrwert.
und dann nach jedem gewählten Filter ein "Ergebnisse anzeigen"

**Comment by wrcg** [comment]
https://inpsyde.atlassian.net/jira/software/c/projects/FAU/issues/FAU-380

**Comment by wrcg** [comment]
![image](https://github.com/RRZE-Webteam/FAU-Studium/assets/9526974/196c287f-f2d3-43a8-a72b-2ba35d08f243)
Wenn der Filter automatisch geladen hat, bleibt das Dropdown stehen. Absicht?

**Comment by xwolfde** [comment]
Für mich passt das alles.
Auch auf Small Screen und Tastatureingaben.

=> ok.
