### ISSUE TITLE
Suche nach Begriffen einschränken

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Studium#116]
Erste Verbesserungsversuche mit den zu durchsuchenden Feldern starten:  Ausschluss der Felder Studienrichtungen und Schwerpunkte und folgende.

Konkret soll die Suche nach einem Begriff nur noch die folgenden Felder durchsuchen:

* Titel,
*  Subtitel,
* Worum geht es im Studiengang (What is the degree program about?)

Diskussion dazu unter #91

**Comment by wrcg** [comment]
https://inpsyde.atlassian.net/jira/software/c/projects/FAU/issues/FAU-377

**Comment by xwolfde** [comment]
Beispielsuche mit "Physik":

Findet u.a. Biologie Lehramt:
https://fau-studium-verwaltung.dev.cms.rrze.de/studiengang/biologie-lehramt/

Dort ist "Physik" in keiner der 3 o.g. Felder, sondern in "Besondere Hinweise" ("Special Features")

**Comment by xwolfde** [comment]
Passt.
Hinweis: Ein Invalidation war notwendig, da die zu durchsuchenden Felder als Suchstring zusammengebaut wurden. (sWarum hat man da nicht Joins über die Datenfelde rgemacht,? Egal.)
