### ISSUE TITLE
Erweiterung der Ausgabe bei der Listenform

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Studium#121]
Es soll ermöglicht werden, dass man die Ausgabe der Studiengänge in Listenform in den jeweiligen Spalten beeinflusst, nämlich dass angegebenen Spalten entfernt und andere hinzugefügt werden können.

Hierzu muss der Shortcode ergänzt werden um entsprechende show/hide-Parameter.

Beispiele:
` [fau-studium display="search" show="Sprachnachweise"]` - ergänzt die vorhandene Listenausgabe um eine Spalte der Sprachnachweise und befüllte dies in den jeweiligen Reihen mit den Inhalts aus dem Feld. Neue zusätzliche Felder, werden immer am Ende als neue Spalte ergänzt. 

` [fau-studium display="search" hide="Ort"]` - lässt in der vorhandenen Listenausgabe die Spalte Ort weg.

` [fau-studium display="search" show="Sprachnachweise, LinkStudiengang"]` - ergänzt die vorhandene Listenausgabe um eine Spalte der Sprachnachweise und den Link zur Studiengangswebsite in der eingegebenen Form.

**Umsetzungshinweise:**

Damit die Show- und Hide-Parameter möglichst fehlerfrei eingegeben werden können und klar definiert sind, wird eine Liste der Variablennamen ausgehend von den Ids/Namen der Backendeingabe vorgegeben.  Obige Beispiele der Parameter sind rein fiktiv und sollen dann später die richtigen Variablennamen nutzen.
Die Liste der verfügbaren Variablennamen soll bereitgestellt werden.
Die jeweiligen Inhalte werden ohne Änderung angezeigt; z.B. bei Links dann auch die URL so wie sie eingegeben wurde und nicht ein Linkname.

Ref: https://inpsyde.atlassian.net/browse/FAU-400

**Comment by wrcg** [comment]
passt
