### ISSUE TITLE
Sicherheitsupdate nötig! webpack-dev-middleware to version 5.3.4

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/FAU-Studium#123]
it is possible to access any local file, e.g. /etc/passwd

https://github.com/RRZE-Webteam/FAU-Studium/security/dependabot/17

**Comment by tyrann0us** [comment]
`webpack-dev-middleware` is no longer part of the asset compilation toolchain after the switch to `@wordpress/scripts` in #126.
