### ISSUE TITLE
Datenfelder CPT Studienangebot

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Studium#13]
Ein Studiengang (Custom Post Type) hat folgende Datenfelder:

# Eingabefelder und Daten

## Auf einen Blick

* Titel (Title) entspricht der Studiengangsbezeichnung
* Titel_en (Texteingabefeld)
* Studienbereich (Taxonomie vgl. #14 )
* Untertitel, optional (es sollen z.B. für Studienschwerpunkte Titel mit Untertitel möglich sein (Texteingabe)
* Untertitel_en, optional (Texteingabe)
* Regelstudienzeit (Zahl, Anzahl Semester)
* Kostenpflichtig (Auswahlfeld ja/nein - Anzeige nur, wenn "ja" gewählt)
* Studienbeginn (Taxonomie, vgl. #16)
* Studierendenzahl-komplett (Zahl)
* Unterrichtssprache (Taxonomie,  vgl . #28 )
* Attribut (Taxonomie, vgl. #20)
* Abschluss (Taxonomie, vgl. #15)
* Fakultät  (Taxonomie, vgl. #19)
* Studienort (Taxonomie, vgl. #17)
* Fächergruppe (Taxonomie, vgl. #18)
* Symbolbild (Artikelbild, wird dann u.a. für die Kacheln verwendet)
* Videos (URL) - mehrere Videos sollen möglich sein (evtl. mit Links zu weitere Videos zu diesem Studiengang) 

* Metadescription (Texteingabe, max. Zeichenlänge 160 Zeichen)
* Metadescription_en (Texteingabe, max. Zeichenlänge 160 Zeichen)

## Inhalte

* Worum geht es im Studiengang? (Editoreingabefeld)
* Worum geht es im Studiengang_en (Editoreingabefeld)

* Aufbau und Struktur (Editoreingabefeld)
* Aufbau und Struktur_en (Editoreingabefeld)

* Studienrichtungen und Schwerpunkte, optional (Editoreingabefeld)
* Studienrichtungen und Schwerpunkte_en, optional (Editoreingabefeld)

* Kombinationsmöglichkeiten, optional (Taxonomie vgl. #55)

* Was sollte ich mitbringen?, optional (Editoreingabefeld)
* Was sollte ich mitbringen?_en, optional (Editoreingabefeld)

* Gute Gründe für ein Studium an der FAU, optional (Editoreingabefeld)
* Gute Gründe für ein Studium an der FAU_en, optional (Editoreingabefeld)

* Welche beruflichen Perspektiven stehen mir offen?, optional (Editoreingabefeld)
* Welche beruflichen Perspektiven stehen mir offen?_en, optional (Editoreingabefeld)

* Besondere Hinweise, optional (Editoreingabefeld)
* Besondere Hinweise_en, optional (Editoreingabefeld)
* Erfahrungsberichte, optional (Editoreingabefeld, v.a. für Videoeinbindung, aber ggfs. auch kurze Testimonials oder Links zu anderen Seiten)
* Erfahrungsberichte_en, optional (Editoreingabefeld, v.a. für Videoeinbindung, aber ggfs. auch kurze Testimonials oder Links zu anderen Seiten)

## Gruppe Zugangsvoraussetzungen, Bewerbung und Einschreibung: 

###Bachelor/Lehramt
* Zugangsvoraussetzungen_Bachelor/Lehramt_1_Fachsemester (Taxonomie mit Text und LinkURL vgl. #21)
* Zugangsvoraussetzungen_Bachelor/Lehramt_höheres_Semester (Taxonomie mit Text und LinkURL vgl. #21) - Feld ist nur erforderlich, wenn bei Zugangsvoraussetzungen 1. Fachsemester NC oder Voranmeldung ausgewählt wurde

###Master
* (formale) Zugangsvoraussetzungen_Master (Taxonomie mit Text und LinkURL vgl. #21)
* inhaltliche Zugangsvoraussetzungen_Master (Editoreingabefeld)
* inhaltliche Zugangsvoraussetzungen_Master_en (Editoreingabefeld)
* Bewerbungsfrist_Wintersemester (Zahl oder Datum ohne Jahreszahl)
* Bewerbungsfrist_Sommersemester (Zahl oder Datum ohne Jahreszahl) - wird nicht angezeigt, wenn bei Taxonomie Semester Sommersemester nicht gewählt ist

###für Bachelor/Lehramt/Master
* Details_und_Anmerkungen (Editoreingabefeld)
* Details_und_Anmerkungen_en (Editoreingabefeld)
* Sprachkenntnisse  (Editoreingabefeld)  
* Sprachkenntnisse_en  (Editoreingabefeld)  
* Sprachkenntnisse nur PhilFak (Konstante, vgl. #22)
* Sprachnachweise/Deutschkenntnisse für internationale Bewerberinnen und Bewerber (Taxonomie, vgl. #44)

## Gruppe Organisation (Organisatorische Hinweise/Links)
* Semesterstart (Konstante  vgl. #22) 
* Semestertermine (Konstante vgl. #22) 
* Prüfungsamt (Taxonomie vgl. #56)  
* Studien- und Prüfungsordnung (Taxonomie vgl. #56)  
* Modulhandbuch (URL-Eingabefeld)
* Studiengang-URL (URL-Eingabefeld)
* Studiengang-URL-en (URL-Eingabefeld)
* Department (URL-Eingabefeld)
* Allgemeine Studienberatung (Konstante  vgl. #22)
* Beratung aus dem Fach (Taxonomie, vgl. #57)
* Beratungs- und Servicestellen der FAU (Konstante  vgl. #22)
* Bewerbung (Taxonomie, vgl. #53)
* Studierendenvertretung/FSI (URL)
* Semesterbeitrag (Konstante  vgl. #22)
* Studiengangsgebühren (Editoreingabefeld)
* Studiengangsgebühren_en (Editoreingabefeld)
* Wege ins Ausland (Konstante vgl. #22)

## zusätzlich
* Schlagworte (vgl. #23)
* Konstanten (Hinweis zu Konstanten vgl. #49)

**Comment by wrcg** [comment]
Vorgaben für Lehramtsstudiengänge definieren - wie werden Fächer und Schularten miteinander verknüpft und dargestellt?

**Comment by wrcg** [comment]
Editoreingabefelder sollen Dateiupload ermöglichen und Shortcode (z.B. für Videos) akzeptieren

**Comment by wrcg** [comment]
ausgewählte Anzeige - sowohl bei der Eingabe (als auch später bei der Ausgabe):
- Kostenpflichtig - ja/nein bei ja: Anzeige des Feldes "Studiengangsgebühren"
- bei Auswahl der Fakultät und Abschluss: bei "Phil und BA" oder "Nat und BA" -> Anzeige der Kombinationsmöglichkeiten für 2-Fach-Bachelor 
- bei Auswahl von Abschluss: bei "Bachelor" und "Lehramt" -> Zugangsvoraussetzungen Paket Bachelor/Lehramt
- bei Auswahl von Abschluss: bei "Master" -> Zugangsvoraussetzungen Paket Master
- bei Auswahl von Abschluss und Fakultät: bei "Bachelor", "Phil" und "Lehramt": -> Feld Sprachkenntnisse_phil anzeigen

**Comment by wrcg** [comment]
**Auf einen Blick**
Titel (Title) entspricht der Studiengangsbezeichnung (Beschreibung für Autoren: "_Studiengangsbezeichnung, ohne Abschluss_")

Titel_en (Texteingabefeld) 
Studienfach (Taxonomie vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/14 ) 

Untertitel, optional (es sollen z.B. für Studienschwerpunkte Titel mit Untertitel möglich sein (Texteingabe) (Beschreibung für Autoren: "_z.B. Aufzählung der Studienschwerpunkte bei Wirtschaftswissenschaften_")

Untertitel_en, optional (Texteingabe)

Regelstudienzeit (Zahl, Anzahl Semester)

Kostenpflichtig (Auswahlfeld ja/nein - Anzeige nur, wenn "ja" gewählt)  (Beschreibung für Autoren: "_Studiengangsgebühren, nicht Semesterbeiträge_")

Studienbeginn (Taxonomie, vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/16)

Studierendenzahl-komplett (Zahl) (Beschreibung für Autoren: "_Gesamtzahl der Studierenden, nicht nur Erstsemester_") 
Ergänzung: hier besser eine Auswahlmöglichkeit/Taxonomie statt ein freies Feld für Zahl vorgeben: <50, 50 - 150, 150-250, 250 - 500/600, >500/600

Unterrichtssprache (Taxonomie, vgl . https://github.com/RRZE-Webteam/FAU-Studium/issues/28)

Attribut (Taxonomie, vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/20)

Abschluss (Taxonomie, vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/15)

Fakultät (Taxonomie, vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/19)

Studienort (Taxonomie, vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/17)

Fächergruppe (Taxonomie, vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/18)

Symbolbild (Artikelbild, wird dann u.a. für die Kacheln verwendet) (Beschreibung für Autoren: "_wird u.a. für die Kacheln auf der Auswahlseite verwendet_")

Videos (URL) - mehrere Videos sollen möglich sein (evtl. mit Links zu weitere Videos zu diesem Studiengang) (Beschreibung für Autoren: "_Videos über den Studiengang, das Studienfach, ein Thema des Fachs (z.B. 2-Minuten-Wissen), Erfahrungsberichte_")

Metadescription (Texteingabe, max. Zeichenlänge 160 Zeichen)  (Beschreibung für Autoren: "_Text für die Anzeige bei Suchmaschinen_")

Metadescription_en (Texteingabe, max. Zeichenlänge 160 Zeichen) 

**Inhalte**
Worum geht es im Studiengang? (Editoreingabefeld) (Beschreibung für Autoren: "_Vorstellung des Fachs und der Studieninhalte" +/-200 Wörter_)


Worum geht es im Studiengang_en (Editoreingabefeld) 

Aufbau und Struktur (Editoreingabefeld) (Beschreibung für Autoren: "_Phasen des Studiums und deren Inhalte, +/-200 Wörter_)

Aufbau und Struktur_en (Editoreingabefeld) 

Studienrichtungen und Schwerpunkte, optional (Editoreingabefeld) (Beschreibung für Autoren: "_Spezialisierungsmöglichkeiten und Schwerpunkte während des Studiums, +/-200 Wörter_")

Studienrichtungen und Schwerpunkte_en, optional (Editoreingabefeld) 
Kombinationsmöglichkeiten, optional (Taxonomie vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/55)

Was sollte ich mitbringen?, optional (Editoreingabefeld) (Beschreibung für Autoren: "_Fähigkeiten und Vorlieben der Studieninteressierten, nicht formelle Voraussetzungen +/-200 Wörter_")

Was sollte ich mitbringen?_en, optional (Editoreingabefeld) 

Gute Gründe für ein Studium an der FAU, optional (Editoreingabefeld) (Beschreibung für Autoren: "_Einzigartigkeit bzw. Besonderheiten des Studiengangs an der FAU +/-200 Wörter_")

Gute Gründe für ein Studium an der FAU_en, optional (Editoreingabefeld) 

Welche beruflichen Perspektiven stehen mir offen?, optional (Editoreingabefeld)  (Beschreibung für Autoren: "_mögliche Tätigkeitsfelder nach Abschluss des Studiums +/-200 Wörter_")

Welche beruflichen Perspektiven stehen mir offen?_en, optional (Editoreingabefeld)  

Besondere Hinweise, optional (Editoreingabefeld)  (Beschreibung für Autoren: "_Möglichkeiten von Auslandsaufenthalten, Kooperationen mit Forschungsprojekten, etc. +/-200 Wörter_)

Besondere Hinweise_en, optional (Editoreingabefeld)

Erfahrungsberichte, optional (Editoreingabefeld, v.a. für Videoeinbindung, aber ggfs. auch kurze Testimonials oder Links zu anderen Seiten) (Beschreibung für Autoren: "_Videos oder Links zu schriftlichen Testimonials, Einbindung von studycheck-Bewertungen_)

Erfahrungsberichte_en, optional (Editoreingabefeld, v.a. für Videoeinbindung, aber ggfs. auch kurze Testimonials oder Links zu anderen Seiten)

Gruppe Zugangsvoraussetzungen, Bewerbung und Einschreibung:
###Bachelor/Lehramt

Zugangsvoraussetzungen_Bachelor/Lehramt_1_Fachsemester (Taxonomie mit Text und LinkURL vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/21)
Zugangsvoraussetzungen_Bachelor/Lehramt_höheres_Semester (Taxonomie mit Text und LinkURL vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/21) - Feld ist nur erforderlich, wenn bei Zugangsvoraussetzungen 1. Fachsemester NC oder Voranmeldung ausgewählt wurde
###Master

(formale) Zugangsvoraussetzungen_Master (Taxonomie mit Text und LinkURL vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/21)
inhaltliche Zugangsvoraussetzungen_Master (Editoreingabefeld)  (Beschreibung für Autoren: "_vorausgegangene Bachelorstudiengänge, Qualifikationswerte, etc._")
inhaltliche Zugangsvoraussetzungen_Master_en (Editoreingabefeld)
Bewerbungsfrist_Wintersemester (Zahl oder Datum ohne Jahreszahl)
Bewerbungsfrist_Sommersemester (Zahl oder Datum ohne Jahreszahl) - wird nicht angezeigt, wenn bei Taxonomie Semester Sommersemester nicht gewählt ist
###für Bachelor/Lehramt/Master

Details_und_Anmerkungen (Editoreingabefeld)  (Beschreibung für Autoren: "evtl. zusätzliche Infos zu Bewerbung und Einschreibung")
Details_und_Anmerkungen_en (Editoreingabefeld)
Sprachkenntnisse (Editoreingabefeld)  (Beschreibung für Autoren: "_Sprachkenntnisse, die für den Studiengang erforderlich sind_")
Sprachkenntnisse_en (Editoreingabefeld)
Sprachkenntnisse nur PhilFak (Konstante, vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/22)  (Beschreibung für Autoren: "_Sprachkenntnisse, die auch in den ersten Semestern noch erworben werden können_")
Sprachnachweise/Deutschkenntnisse für internationale Bewerberinnen und Bewerber (Taxonomie, vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/44)


Gruppe Organisation (Organisatorische Hinweise/Links)
Semesterstart (Konstante vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/22)
Semestertermine (Konstante vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/22)
Prüfungsamt (Taxonomie vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/56)
Studien- und Prüfungsordnung (Taxonomie vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/56)
Modulhandbuch (URL-Eingabefeld)
Studiengang-URL (URL-Eingabefeld)
Studiengang-URL-en (URL-Eingabefeld)
Department (URL-Eingabefeld)
Allgemeine Studienberatung (Konstante vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/22)
Beratung aus dem Fach (Taxonomie, vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/57)
Beratungs- und Servicestellen der FAU (Konstante vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/22)
Bewerbung (Taxonomie, vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/53)
Studierendenvertretung/FSI (URL)
Semesterbeitrag (Konstante vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/22)
Studiengangsgebühren (Editoreingabefeld) (Beschreibung für Autoren: "_Kosten des Studiums bei kostenpflichtigen Studiengängen, nicht Semesterbeitrag_")
Studiengangsgebühren_en (Editoreingabefeld)
Wege ins Ausland (Konstante vgl. https://github.com/RRZE-Webteam/FAU-Studium/issues/22)



-> bei den Taxonomien und überall, wo wir bereits "descriptions" haben, können wir als Hilfetexte die Beschreibungen verwenden. So können wir hier ggfs. individuell nachbessern.
