### ISSUE TITLE
Datenfelder Konstanten (Taxonomie oder Setting)

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Studium#22]
Taxonomie/Setting mit den Defaultfelder Name, Titelform und Beschreibiung, sowie zusätzlich Linktext und Linkurl.

Eingabefelder für englischen Namen, Beschreibung, Link ergänzen.

![grafik](https://user-images.githubusercontent.com/1070669/170674392-263f4b3f-3eb3-4278-9827-4a9c4a1b7790.png)

**Comment by wrcg** [comment]
zusätzliche Konstante: "Dieser Studiengang kann dual studiert werden" mit Link zur entsprechenden Webseite, 
Filtermöglichkeit nach dualen Studiengängen bei der Ausgabe vorsehen

**Comment by xwolfde** [comment]
wurde umgesetzt in den Settings.
Ab der Version 007 auch mit Tabs (vorher waren es zwei verschiedene Settings-Seiten).
https://meinstudium.cms.rrze.net/wp-admin/options-general.php?page=fau_degree_program_settings&tab=fau_degree_program_shared_properties
