### ISSUE TITLE
WordPress-Capabilites/ Rollen ergänzen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Studium#26]
Zur Bearbeitung der Daten werden wir zusätzliche Rollen benötigen um ein egewisse redaktionelle Kontrolle zu ermöglichen.

* "Studienangebotsautor" (Aktuell bereits im Plugin fau-studienangebot)
     *  Kann Studienangebote anlegen und bearbeiten und die eigenen Angebote publizieren. 
* "Studienangebotsredakteuer" 
     *  Kann Studienangebote anlegen, bearbeiten und publizieren, sowie auch Taxonomien anlegen, bearbeiten und publizieren.

**Comment by wrcg** [comment]
evtl. 
* "Studienangebotsautor-Fakultät" - kann Studienangebote einer ausgewählten Fakultät bearbeiten und publizieren.

**Comment by xwolfde** [comment]
Umsetzungshinweis:
Über das im CMS verwendete SSO-System werden die Benutzer angelegt. Die Benutzer im CMS werden daher nicht händisch registriert oder angelegt. Über das SSO-System werden nicht nur die Basis-Nutzerdaten (E-Mailadresse, Vorname, Nachname) übergeben, sondern auch Affilations des Benutzers. Beispielsweise seine Rolle an der FAU als student oder employee aber auch Zugehörigkeiten zu Einrichtungen sowie weitere definierbare Attribute.
Die o.g. Rollen sollen daher automatisch über die Affilation gesetzt bzw. geändert werden. Diese Funktion (Setzen und Ändern der Affikations und Rollen) geschieht jedoch ausserhalb des hier definierten Plugins.
Für das Plugin ist es jedoch notwendig, dass diese Rolle existierten und Nutzern zuordnbar sind.

Die genaue Matrix, welche einzelnen CPT und CPF durch welche Rollen bearbeitbar sind (zusätzlich zu den oben gegebenen groben Angaben), wird im Rahmen der Umsetzung gemeinsam abgestimmt.

**Comment by xwolfde** [comment]
Die beiden Rollen existieren zwar, aber diese haben aif der 0.0.7 aktuell noch lesenden und schreibenden Zugriff sowohl auf Taxonomien als auch Settings. Auch der AUthor, der z.b. Settings nicht sehen sollte

**Comment by xwolfde** [comment]
wurde umgesetzt
