### ISSUE TITLE
Taxonomie Datenfelder Unterrichtssprache

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Studium#28]
In fau.de bislang als Texteingabefeld, bei MeinSTudium bereits Taxonomie.

Felder:
Name, Beschreibung, Titelform plus zusätzlich Eingabefelder für engl. Name und Beschreibung

Aktuell auf meinstudium:
![grafik](https://user-images.githubusercontent.com/1070669/170682565-f927e8fd-f1e0-49d9-86f5-3b5e165f4642.png)

**Comment by xwolfde** [comment]
In 0.0.6 fehlt noch die englische Beschreibung:
<img width="1622" alt="grafik" src="https://user-images.githubusercontent.com/1070669/226633024-c429ee39-8500-4bca-8b9c-31e31e4f79ac.png">

Frage an @wrcg Wird der Beschreibungstext eigentlich irgendwo gebraucht? Auf der Prod sind bei den 4 Feldern auch gar keine deutschen Texte eingegeben.  Statt das fehlende Feld zu ergänzen würde ich das Field zur Beschreibung weglassen (oder nur intern verwenden).
Bei der Bearbeitung sollte auch der Slug (Titelform) sprachlich neutral gehalten werdeen, aber dies ist Sache der Administration.

Ich würde diesen Issue ansonsten als erfüllt betrachten und das Entfernen des nicht mehr nötigen Beschreibungsfeld als unwichtiges Nice to have in V4 sehen.

**Comment by wrcg** [comment]
Beschreibungsfeld wird aktuell nicht verwendet, Issue kann geschlossen werden.
