### ISSUE TITLE
Darstellungsform der SG-Übersicht: Kachelformat

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Studium#3]
Darstellung der Studiengänge im Kachelformat und Listenformat jeweils mit

- Bild
- Titel des Studiengangs

**Comment by wrcg** [comment]
bis zu drei Korrektur-/Anpassungsschleifen bei der optischen Gestaltung sollen inklusiv sein

**Comment by wrcg** [comment]
Es soll möglich sein, die Reihenfolge der Kachelauswahl zu beeinflussen. 
z.B. bei der Auswahl "Lehramt" sollen alle Lehramtsmöglichkeiten (Grundschule, Mittelschule,...) zuerst/oben angezeigt werden und danach die Fächer

**Comment by xwolfde** [comment]
Kann erst mit dem Embed-Plugin getestet werden/Ausgabe ist Teil von diesem. Ggf. dahin schieben?

**Comment by xwolfde** [comment]
wurde gemacht
