### ISSUE TITLE
Gestaltung Studiengang als Webseiten-Ausgabe

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Studium#31]
Gemäß der Angaben aus #7 und #13 ist eine optische Gestaltung für ein CPT eines Studiengang zu entwerfen.
DIese sollte die wichtigstens Daten attraktiv und übersichtlich darstellen .Dabei ist das Plugin zusammen mit dem Theme FAU-Einrichtungen zu verwenden.

Die Ausgabe kann sich an den vorhandenen Ausgaben orientieren, soll aber folgende Verbesserungen mitbringen:
* Die Darstellung muss Barrierefrei gemäß WCAG 2.1 AA sein
* soweit sinnvoll, sollen HTML-Ausgaben mittels strukturierten Daten angereichert werden (vgl. schema.org). Wünschenswert ist auch eine Berücksichtigung von Education QA https://developers.google.com/search/docs/advanced/structured-data/education-qa?hl=de 

bis zu drei Korrektur-/Anpassungsschleifen bei der optischen Gestaltung sollen inklusiv sein
responsive Design, gerne auch mobile first

**Comment by xwolfde** [comment]
Die Anforderungen dieses Issues werden ebenfalls bei dem [FAU Studium Embed Plugin](https://github.com/RRZE-Webteam/FAU-Studium-Embed/issues) gefordert.

**Comment by wrcg** [comment]
Die 5 Farben, die aktuell auf meinstudium für die fünf Fakultäten verwendet werden, sind veraltet. Die neuen Farbwerte sind hier: https://www.wordpress.rrze.fau.de/entwicklung/design/farben/

**Comment by xwolfde** [comment]
wurde gemacht
