### ISSUE TITLE
komfortables Backend für Autoren

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Studium#40]
Die Eingabe für Autoren soll komfortabel gestaltet werden, d.h. z.B.
- strukturierte Eingabelisten, z.B. an der Ausgabe im Frontend orientiert, in Widgets geclustert, mit Dropdown-Menüs, etc.  - gerne Vorschläge machen!
- englische und deutsche Eingabefelder optisch unterscheidbar
- Eingabefelder werden erst nach und nach sichtbar, wenn bestimmte Felder angeklickt werden
- Individuelle Eingabemasken nach Art des Studiengang (Bachelor, Lehramt, Master, Weiterbildung)
- kurze Erklärtexte/Ausfüllhilfen bei Feldern 

* optional: Kombinationsmöglichkeiten 
    * (multi)Auswahlfeld zu schaffen,  mit dem andere vorhandene Studiengänge ausgewählt werden können.
   * Beispiel meinstudium: 
![grafik](https://user-images.githubusercontent.com/1070669/170681600-542fb772-5012-4731-903c-e1b960007003.png)
   * Diese Option soll nur erscheinen bei Studiengängen, die als Taxonomie Abschluss einen Wert für Bachelor oder Lehramt haben

Felder zu Zugangs-/Sprachvoraussetzungen erscheinen je nach Wert der Taxonomie Abschluss 

Zu beachten ist, dass die Eingabe zunächst in einer ClassicEditor-Umgebung laufen soll. Falls in Zukunft von der Website als ganzes oder einzelnen AUtoren auf den Block Editor umgestellt wird, soll die Oberfläche Bestand haben.

**Comment by xwolfde** [comment]
Noch zu definieren: Welche Felder werden in welcher Kombination sichtbar oder werden ausgeblendet.

**Comment by wrcg** [comment]
ausgewählte Anzeige - sowohl bei der Eingabe (als auch später bei der Ausgabe):

- kostenpflichtig - ja/nein bei ja: Anzeige des Feldes "Studiengangsgebühren"
- bei Auswahl der Fakultät und Abschluss: bei "Phil und BA" oder "Nat und BA" -> Anzeige der Kombinationsmöglichkeiten für 2-Fach-Bachelor
-bei Auswahl von Abschluss: bei "Bachelor" und "Lehramt" -> Zugangsvoraussetzungen Paket Bachelor/Lehramt
-bei Auswahl von Abschluss: bei "Master" -> Zugangsvoraussetzungen Paket Master
-bei Auswahl von Abschluss und Fakultät: bei "Bachelor", "Phil" und "Lehramt": -> Feld Sprachkenntnisse_phil anzeigen

**Comment by xwolfde** [comment]
Nach gemeinsamer Abstimmung: Das Backend wurde nicht mit dem Classic Editor und Tools wie CMB2 o.ä. umgesetzt sondern in einem angepassten Block Editor.

Umsetzung weitestgehend erfüllt. 
Noch offen in 0.0.6 sind jedoch die Punkte:

- [ ] Eingabefelder werden erst nach und nach sichtbar, wenn bestimmte Felder angeklickt werden
- [ ] bei Auswahl der Fakultät und Abschluss: bei "Phil und BA" oder "Nat und BA" -> Anzeige der Kombinationsmöglichkeiten für 2-Fach-Bachelor
- [ ] bei Auswahl von Abschluss: bei "Bachelor" und "Lehramt" -> Zugangsvoraussetzungen Paket Bachelor/Lehramt
- [ ] bei Auswahl von Abschluss: bei "Master" -> Zugangsvoraussetzungen Paket Master
- [ ] bei Auswahl von Abschluss und Fakultät: bei "Bachelor", "Phil" und "Lehramt": -> Feld Sprachkenntnisse_phil anzeigen

**Comment by xwolfde** [comment]
mit 007 erfüllt
