### ISSUE TITLE
HTML-Eingabefelder: Eingeschränkter Satz an HTML-Tags

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Studium#41]
Bei Eingabefeldern für Studiengangsdaten, bei denen HTML wünschenswert ist, wird nur ein eingeschränktes Setup an HTML-Tags erlaubt:

- ul
- li
- ol
- strong
- a
- br
- p
- img, picture
- h3, h4, h5  (h1-h2 sind nicht erlaubt, da diesese hierachisch schon darüber verwendet werden)

Sowie folgenden Shortcodes (inkl. Parametrisierung):
- [alert]
- [kontakt]
- [fau-video]

Keine Attribute!

**Comment by xwolfde** [comment]
Add: Please dont allow the style=""  attribut in any HTML-Tag.

By using wp_kses() use this array for allowed HTML (please put this array as constant array somewhere in the settings, so it could be changed later by devs):

```
$allowed_html = array(
	    'img' => array(
			'title' => array(),
			'src'	=> array(),
			'alt'	=> array(),
		),
   'picture' => array(
			'title' => array(),
			'src'	=> array(),
			'alt'	=> array(),
		),
	    'a' => array(
			'title' => array(),
			'href'	=> array(),
			'title'	=> array(),
		),
	    'br' => array(), 
	    'p' => array(), 
	    'strong' => array(),
	    'ul'  => array(),
	    'li'  => array(),
	    'dl'  => array(),
	    'dd'  => array(),
	    'dt'  => array(),
            'h3'  => array(),
           'h4'  => array(),
           'h5'  => array(),
	);
	$value = wp_kses($dateinput,$allowed_html);
```

**Comment by xwolfde** [comment]
LIst-Elemente `ul, ol, li ` gehen nicht und führen zu einer Fehlermeldung. Ebenso die Überschriften h3, h4, h5:

<img width="1434" alt="grafik" src="https://user-images.githubusercontent.com/1070669/226619047-e6824a6c-7879-4a05-938b-8e2c89b16685.png">

Dies sind alles Elemente, die ausserhalb vom Paragraph gesetzt werden und in einem `p` invalide wären.

**Comment by xwolfde** [comment]
Geht doch in den Blöcken mit den Block Editor Funktionen.
Bei Nutzung der HTML-Eingabe kann es zu obigen Fehler kommen. Die Umwandlung in Blöcke (3 Pünkten bei der Meldung) kann das Problem aber dann lösen.

**Comment by wrcg** [comment]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/9526974/226640034-221472a0-6370-4305-bc6d-49066d105d7a.png">
Überschrift H2 kann noch eingestellt werden, bitte entfernen...
