### ISSUE TITLE
Taxonomie zu Studien- und Prüfungsordnungen

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Studium#56]
Felder: Titelform, Name, Beschreibung, Linktext, URL, englischsprachige Übersetzung Linktext, englische URL

hier werden Links zu Prüfungsämter und Prüfungsordnungen eingetragen

**Comment by xwolfde** [comment]
In dem JF 28.02.2023 wurde beschlossen die Taxonomie zu entfernen:

_Überflüssige Taxonomie
Die Taxonomie "Studien- und Prüfungsordnungen“ soll entfernt werden und durch ein Textfeld ersetzt werden, das entweder eine URL oder einen Shortcode aktzeptiert._


Ggf. aber in MIlestone 4 wieder neu denken in Zusammenhang mit https://github.com/RRZE-Webteam/FAU-Studium/issues/45 . Daher wird dieser Issue in den Milestone 4 verschoben.

**Comment by xwolfde** [comment]
Erstmal schliessen.
