### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Studium#6]
Videos von youtube und fau.tv sollen per Shortcode eingebunden werden

**Comment by xwolfde** [comment]
Erläuterung zur Umsetzung:

Bei der auszugebenden Website ist der Shortcode wie folgt anzugeben (um danach via do_shortcode() von WP interpretiert zu werden)

`[fauvideo url="$URL"]`

Im Backend werden nur URLs eingegeben. Diese können dann auch entsprechend der URL-Syntax sanitized werden um Fehleingaben zu erkennen.  Die REST-API soll auch nur die eingebenen URLs (wenn sie valide sanitized wurden) übertragen und nicht bereits duem Umsetzung mittels Shortcode.

vgl. auch: https://www.wordpress.rrze.fau.de/plugins/externe-daten-einbinden/rrze-video/

**Comment by xwolfde** [comment]
umsetzung ok
