### ISSUE TITLE
Social Media Verknüpfungen

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Studium#60]
	SocialMedia Verknüpfungen (Titel, Text und URL-Eingabefeld +  automatisierte Iconverknüpfung)

**Comment by xwolfde** [comment]
Pro Studiengang?

**Comment by wrcg** [comment]
sofern vorhanden: ja

**Comment by xwolfde** [comment]
Wird hierüber lösbar sein: #115
