### ISSUE TITLE
Revisions limitieren

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Studium#64]
Die Änderungen der Studiengangs-Posts werden gemäß https://github.com/RRZE-Webteam/FAU-Studium/issues/46 gesichert.

Damit die Datenbank aber nicht unnötig aufgebäht wird, soll die Anzahl der Revisionendes Post Types `studiengang` auf ein Maximum begrenzt werden.
WICHTIG: Es ist nicht einfach WP_POST_REVISIONS zu verwenden, da die Anzahl der revisionen anderer Post Types der Multisite Instanz nicht beeinflusst werden dürfen. Stattdessen ist mit dem filter `wp_revisions_to_keep` die Limitation auf den Post Type zu begrenzen.

Beispiel:

```
add_filter( 'wp_revisions_to_keep', 'cpt_studiengang_revisions', 10, 2 );
function cpt_studiengang_revisions($num, $post) {
  if('studiengang' == $post->post_type) $num = $ANZAHL;   // Nur ein Beispiel, kommt aus den Settings
  return $num;
}

```

Die $ANZAHL sollte über die Plugin-Settings durch die Admins eingestellt werden können, sollte aber per Default erstmal auf 10 gesetzt werden.  Hierzu ggf. eine eigene Tab in den Settings aufmachen, da es nicht so zu den vorhandenen Tabs mit Texten passt.

**Comment by wrcg** [comment]
ich dachte, das ist schon auf 10 Revisionen beschränkt?
wenn nicht, gerne bei 2.1 dazu.

**Comment by xwolfde** [comment]
wir haben zumindest die option der einschränkung durch uns als Admins nicht

**Comment by xwolfde** [comment]
https://inpsyde.atlassian.net/jira/software/c/projects/FAU/boards/538?selectedIssue=FAU-384

**Comment by xwolfde** [comment]
wurde bereits in V1 gemacht
