### ISSUE TITLE
Taxonomien für Zugangsvoraussetzungen vereinheitlichen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Studium#65]
Die Issue #21 wurde im Milestone 1 in 3 Taxonomien gesplittet.

Dieses macht keinen Sinn und behindert zukünfrtige Ausdehnung auf andere Abschlüsse.

Daher sollten die 3 Taxonomien 

- bachelor_or_teaching_adm_req
- teaching_higher_semester_adm_req
- master_degree_adm_req

wieder zusammengeführt werden in einer einzigen Taxonomy mit dem Slug "degree_requirement"

Für den Abschluss auf den sie sich beziehen, soll zusätzlich eine Multiselect-Auswahl als Field eingefügt werden, die auf den oder die Abschlüsse (=Taxonomy "abschluss") zeigt.

DIes wird in Milestone 3 geschrieben, da dies vor dem Datenaustausch zu Dritten geschehen soll.

**Comment by wrcg** [comment]
sinnvoll? je nach Abschlussart sollen ja andere Auswahlmöglichkeiten angezeigt werden

**Comment by xwolfde** [comment]
stellen wir erstmal zurück
