### ISSUE TITLE
CPT Studiengang

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Studium#7]
Titel, Untertitel

- Bild/Video zum Studiengang

### kurzer Steckbrief mit:#

- Abschluss
- Studienort
- Regelstudienzeit
- Studienbeginn
- Größe
- Fakultät
- Attribute, wie z. B. Elitestudiengang, Weiterbildungsstudiengang
- Bewerben-Button

### Detailinfos mit Freitextfeldern zu:

- Worum geht es im Studiengang?
- Aufbau und Struktur?
- optional: Studienrichtungen und Schwerpunkte
- optional: Kombinationsmöglichkeiten
- optional: Was sollte ich mitbringen?
- optional: Gute Gründe für das Studium an der FAU
- optional: Welche beruflichen Perspektiven stehen mir offen??
- optional: Besondere Hinweise
- optional: Kombinierbare Studiengänge
- Vergleich mit ähnlichen Studiengängen (nicht für Basispaket)

### Zugangsvoraussetzungen, Bewerbung und Einschreibung
- Zugangsvoraussetzungen (je nach Abschlussart aufgeführt für 1. - Fachsemester und ggfs. höheres Fachsemester)
- Bewerbungsfristen (WiSe, bei Bedarf SoSe)
- Details und Anmerkungen
- Sprachkenntnisse (allg. und PhilFak)
- Sprachnachweise/Deutschkenntnisse
- Studiengangsgebühren
- Semesterbeitrag

### Linklisten im Frontend mit Überschriften gliedern (s. meinstudium.fau.de)

- Allgemeinen Studienberatung
- Beratung aus dem Fach
- Beratungs- und Servicestellen der FAU

- Studiengang-Webseite
- Department-Webseite

- Prüfungsamt
- Studien- und Prüfungsordnung

- Studierendenvertretung/FSI
- Wege ins Ausland (allgemein/fachspezifisch)
- Semestertermine
- Semesterstart

### Erfahrungsberichte und spezielle Videos zum Fach

- als Video (Eingabe von ein oder mehrere URLs)
(Umsetzungshinweis: Videos sollen mit Hilfe eines vorhandenen Shortcodes des Plugins RRZE-Video für die Integration von Videos eingebunden werden. Es muss daher keine eigene Videodarstellung entwickelt werden. Zur EIngabe der Videos reicht es daher, die URL des Videos einzugeben und diese als Argument in einem erzeugten Shortcode [fauvideo url="$url"] einzugeben.)

### Anmerkungen

- Die Liste der verfügbaren Datenfelder für den CPT ist in #13 definiert.
- Die Seite eines Studiengangs wird als Custom Post Type festgelegt. Jeder einzelne Studiengang soll so eine eindeutige URL erhalten.
- Die CPTs sollen in der Default-WP-Suche auffindbar sein.

**Comment by xwolfde** [comment]
Die EIngabe der Daten gemäß MIlestone 1.0 und 1.1 sieht für mich erfüllt aus,
Die Ausgabe erfolgt über das gesonderte Plugin.
