### ISSUE TITLE
Technische Grundlagen und Anforderungen an das Plugin

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Studium#8]
## EInzuhaltende Grundbedingungen

Es müssen folgende Grundbedingungen eingehalten werden:

- Plugins sollten stets auf einer WordPress-Installation entwickelt und getestet werden, bei der ein DEBUG-Modus so eingestellt ist, dass er Warnung ausgibt. Kein Plugin darf im produktiven Betrieb Warnings oder gar Fatal Errors liefern.
- Enthält das Plugin JS- oder CSS-Komponenten, muss sichergestellt werden, dass diese nur dann in der WordPress-Installation „enqueued“ werden, wenn das Plugin in der jeweiligen Seite tatsächlich zur Anwendung kommt. Ein grundsätzliches Einbinden auf jeder Seite der Installation ist nicht zulässig. Stattdessen muss ein register() erfolgen und das enqueue() erst dann, wenn ein Shortcode oder eine Funktion ausgeführt wird, die tatsächlich ein Ergebnis ausgibt.
- Bei der Bereitstellung von JS-Dateien ist darauf zu achten, ob etwaige JS-Bibliotheken nicht bereits von WordPress selbst zur Verfügung gestellt werden. In diesem Fall sind die von der WordPress-Instanz zu nutzen. Keinesfalls darf beispielsweise eine eigene jQuery-Bibliothek vom Plugin nochmals mit- und ausgeliefert werden, wenn diese bereits zuvor vom Theme oder einem anderen Plugin ebenfalls enqueued wurde.
- Werden JavaScript-Dateien bereitgestellt, sind diese für die Nutzung im produktiven Einsatz in minifizierter Form bereitzustellen und zur Entwicklung im ungepackten Original
- Werden CSS-Dateien bereit gestellt, die einen Umfang von mehr als 50 Codezeilen (ohne Kommentare) haben, ist zwingend der CSS-Präprozessor SASS zu verwenden. Die CSS-Dateien sollen mit Hilfe von SASS minifiziert werden. Auf die Verwendung von Vendor-Codes in den SASS-Dateien soll verzichtet werden. Vielmehr sollten diese nur mittels eines Autoprefixers in der erzeugten CSS-Datei ergänzt werden. Die CSS-Datei des Plugins sollte den Namen des Plugins tragen und mit .css enden.
- Das Plugin muss als Mindestanforderung kompatibel zur jeweils aktuellen WordPress- und PHP-Version sein. (WordPress-Version 6.0, PHP-Version 8.0)
- Alle HTML-Ausgaben müssen stets konform zur [WCAG 2.1](https://www.w3.org/TR/WCAG21/) in der Konformitätsstufe AA sein. Bei Auftragsvergaben wird die EInhaltung dieses Standards zur Abnahme geprüft. Die Prüfung erfolgt durch das RRZE oder durch externe Tester. Eine Abnahme kann nur erfolgen, wenn keine Mängel bei der Einrhaltung der WCAG vorliegen. Fehler bei der Einhaltung der WCAG werden als Sachmangel gesehen.
- Werden Schriften oder Bibliotheken eingebunden, müssen diese im Source des Plugins vorhanden sein und von dort „lokal“ eingebunden werden. Die Verwendung von externen CDNs (wie beispielsweise fonts.google.com) ist nicht zulässig.
- vgl. auch https://www.wordpress.rrze.fau.de/entwicklung/vorgaben-an-plugins/

## Betriebsumgebung
- Das Plugin wird auf eine Multisite-Instanz (Domain based) eingesetzt.
- Aktuell ist der Block Editor nicht aktiviert. Daher muss das Plugin die Eingabe mittels Classic Editor, bzw. mit Metaboxen unterstützen. Gleichwohl soll für einen zukünftigen Umstieg der Instanz oder einzelner (!) Bediener auf den Block Editor das Plugin auch in der Umgebung mit dem Block Editor lauffähig sein.
- Als Theme wird das Theme [FAU Einrichtungen](https://github.com/RRZE-Webteam/FAU-Einrichtungen) (bzw einer dessen Clones der Fakultäten) verwendet. Zu Entwicklungszwecken soll daher das Theme FAU EInrichtungen genutzt werden.

## Vorgaben
* Das bisher auf www.fau.de verwendete Plugin FAU Studienangebot steht im GitHub zum Download zur Verfügung: https://github.com/RRZE-Webteam/fau-studienangebot . Eine Exportdatei der vorhandenen Daten kann bereit gestellt werden.
* Das auf meinstudium.fau.de entwickelte Theme kann auf Rückfrage als ZIP bereit gestellt werden. Ebenso kann dort ein Zugang eingerichtet werden.
* Die Entwicklung soll in einem eigenen DEV-Branch im Git geleistet werden. Erst bei Fertigstellung wird in den Main-Branch gemergt. Der Main-Branch ist der produktive Branch, der später auf den Instanzen zur Verfügung gestellt wird.
* Es wird empfohlen und vorausgesetzt, dass für die Entwicklung eine selbst verwaltete WordPress-Installation verwendet wird.

**Comment by xwolfde** [comment]
Aktuell gibt es im Backend noch WCAG-Probleme hinsichtlich der Tatstaturbedienung. Diese sind bereits gemeldet.
