### ISSUE TITLE
SocialMedia Empfehlungen hinzufügen

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Studium#81]
Aktuell funktioniert das Plugin Sharif nur auf Seiten, bitte auch bei Studiengängen anzeigen.

**Comment by xwolfde** [comment]
Bitte Details nachliefern. Was meinst du damit?
Welches SoMe und was daraus?

**Comment by xwolfde** [comment]
Duplicate zu #60

**Comment by xwolfde** [comment]
Habs jetzt hier #115 drin
