### ISSUE TITLE
Suchfunktion mangelhaft

### ISSUE THREAD

**Issue by cibsell** [RRZE-Webteam/FAU-Studium#91]
Die Suchfunktion nach einem bestimmten Studiengang unter https://www.fau.de/education/studienangebot/alle-studiengaenge/ sowie https://meinstudium.fau.de/studiengaenge/ ist sehr schlecht. Kann man die Suchergebnisse dort gewichten und nicht alphabetisch reihen? Wer ist dafür verantwortlich, welche Suchergebnisse angezeigt werden? Wer hat die jeweiligen Studiengänge dafür ausgewählt? 

Suche ich z. B. nach Medizin, dann werden mir 34 andere Studiengänge vorgeschlagen (z. B. auch Geschichte Lehramt), bevor ich bei M wie Medizin lande. Beim Suchbegriff Chemie wird zuerst Advanced Materials and Processes und Biologie vorgeschlagen, bevor man dann an 6./ 7. Stelle zu Chemie kommt. Hier wird weiter unten als Suchergebnis Technomathematik, Physik oder Data Science vorgeschlagen, was mit Chemie nicht so viel zu tun hat. Bei Pharmazie erhält man erst an letzter (8.) Stelle den richtigen Treffer. Schaue ich mir die Ergebnisliste für Mathematik oder Physik an, dann sieht das noch schlechter aus – hier erhält man die richtigen Treffer erst weit abgeschlagen nach über 45 anderen Studiengängen, die einem zuvor vorgeschlagen werden. Es stellt sich auch die Frage, wieso Musik Lehramt vorgeschlagen wird, wenn man nach Mathematik oder Physik sucht? 

Bitte ändern Sie die Reihung in der Ergebnisliste. So macht sie überhaupt keinen Sinn. Wenn es z. B. einen Studiengang wie „Mathematik“ gibt, sollte dieser zuerst in der Ergebnisliste auftauchen, danach alle Studiengänge mit sehr hohem Mathematikanteil, z. B. Technomathematik, Wirtschaftsmathematik oder Data Science und danach weitere Studiengänge mit Nebenfach Mathematik. Konsekutive Masterstudiengänge wie z. B. Zell- und Molekularbiologie sollten direkt bei ihren jeweiligen Bachelorstudiengängen (Biologie) auftauchen und nicht an letzter Stelle unter Z. Es ist auch nicht logisch, dass in den Suchergebnissen die Lehramtsstudiengänge vor den Bachelorstudiengängen gelistet werden, z. B. Biologie (Lehramt) vor Biologie (B.Sc.), wenn die übrige Sortierung alphabetisch ist.

**Comment by xwolfde** [comment]
Haben wir inzwischen konkrete Vorschläge?

**Comment by wrcg** [comment]
die Verbesserung der Suche ist aus meiner Sicht Teil des Workshops mit der Agentur

**Comment by xwolfde** [comment]
Also was nun?

**Comment by wrcg** [comment]
erste Verbesserungsversuche mit den zu durchsuchenden Feldern starten: Ausschluss der Felder Studienrichtungen und Schwerpunkte und folgende

Konkret durchsucht die Suche dann nur noch:
- Titel, 
- Subtitel,
- Worum geht es im  Studiengang (What is the degree program about?)

**Comment by xwolfde** [comment]
Habs als eigenen Issue ohne Diskussionen angelegt.
