### ISSUE TITLE
Verknüpfung der deutschen und englischen Studiengangsseite über den Sprachwechsler

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Studium#92]
aktuell gelangt man beim Klick auf den Sprachwechsler wieder auf die Übersichtsseite alle Studiengänge und nicht direkt zum ausgewählten Studiengang.

**Comment by xwolfde** [comment]
Wird über ein anderes Plugin gemacht.
Aber: Wenn #100 hier erstmal umgesetzt wurde, dann kann das Plugin dies in Folge auch richtig lösen.

**Comment by xwolfde** [comment]
Issue in  #100  genauer beschrieben
