### ISSUE TITLE
frei gestaltbare Links ermöglichen

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Studium#94]
für den Linkblock am unteren Ende eines Studiengangs wird mehr Flexibilität gewünscht:
zwei bis drei frei wählbare Linkfelder einfügen, um Linktext und URL frei bestimmen zu können 
(z.B. für saisonale Infos GOS zum WS oder ZfL-Begrüßungsseite für Neustudierende)

**Comment by xwolfde** [comment]
Könnten wir über #73 lösen

**Comment by xwolfde** [comment]
Das bedeutet dann ein pro Studiengang zusätzlicher Inhaltsbereich, indem man den Link-Block verwenden kann?

Soll das an den vorhandenen Links angefügt werden, also an die dortige Liste oder ein Extrabereich darstellen. Bitte mit Wireframes erklären.

**Comment by xwolfde** [comment]
Moment, dies ist ein Duplicate zu #84 . Cathrin, bitte klären, was da gewünscht ist und einen Issue löschen

**Comment by wrcg** [comment]
das ist kein Duplikat. Wireframe kommt!

**Comment by xwolfde** [comment]
Ich hab hierzu mal hier ein damit zusammenhängenden Issue gemacht: #115

**Comment by xwolfde** [comment]
Ist wie vorhoin besprochen in 115
