### ISSUE TITLE
Schlagworte für den Interessenten sichtbar machen

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Studium#97]
die im Backend je Studiengang vergebenen Schlagworte könnten auch im Frontend sichtbar gemacht werden und mit Hilfe einer Art Tagcloud klickbar gemacht werden.
Sinnvoll/notwendig?

**Comment by xwolfde** [comment]
Ich halte es für sehr sinnvoll

**Comment by wrcg** [comment]
Die aktuell vergebenen Schlagworte ähneln den späteren Studienfachanteilen und den aktuellen Studienbereichen. Sie können im Zuge der Überarbeitung der Studienfachanteile/Studienbereiche aufgelöst werden. 
Sie für den Interessenten sichtbar machen ist deswegen nicht mehr erforderlich.
(Studienfachanteile sind sichtbar und sollen klickbar sein)

(mit IBZ 4.10.)

**Comment by xwolfde** [comment]
ich glaube nicht, dass Leute, die ein Studium suchen, diese Ansicht teilen. Und um die geht es uns und nicht um Verwaltungsfachangestellte, die seit Jahrzenten den Job machen .. :P 
Hier sollten wir Rücksprache mit STUVE u.a. halten.

**Comment by wrcg** [comment]
Schlagworte erst entfernen, wenn Studienfachanteile vorhanden sind,
werden bis dahin auch in der Suche mit durchsucht

**Comment by wrcg** [comment]
ok, gute Argument. 
In der Regel sind aber die Schlagworte auch Begriffe, die im Beschreibungstext vorkommen. Wenn wir also die Schlagworte vorerst in der Suche lassen und die Texte aus den Textblöcken aus der Suche ausschließen, würde es zum einen nicht auffallen und zum anderen die Ergebnisse der Suche vielleicht doch trennschärfer werden.

**Comment by xwolfde** [comment]
Na, ich würde es andersrum machen. Die Texte sieht der Benutzer ja. Also sieht er daran, warum er den Treffer bekam.
Bei den unsichtbaren Schlagworten hingegen kann es welche geben, die nicht im Text auftauchen.

**Comment by wrcg** [comment]
Schlagworte werden nicht mehr benötigt
