### ISSUE TITLE
Suchmaske: Reihenfolge der Auswahlmöglichkeiten ändern

### ISSUE THREAD

**Issue by wrcg** [RRZE-Webteam/FAU-Studium#98]
Reihenfolge bitte ändern in:
Direkte Anzeige:
1.	Abschluss
2.	Fächergruppe
3.	Besondere Studienformen

Erweiterte Filter
•	Fakultät
•	Studienfachanteile (jetzt heißt dieser Teil noch Studienbereich, wird inhaltlich noch angepasst)
•	Studienbeginn
•	Studienort
•	Unterrichtssprache
•	**neu:** Zugang (nur Oberkategorien wie bei Abschluss anzeigen, also eingeschränkt (NC), zulassungsfrei, zulassungsfrei mit Einschränkung)

(am 4.10. mit IBZ finalisiert)

**Comment by xwolfde** [comment]
Die Reihenfolge passt.

Aber die erwieterten Filter scrollen nun bis in den Marianengraben tief...

Da wird nach rechts nicht gewrappt.
<img width="1482" alt="grafik" src="https://github.com/RRZE-Webteam/FAU-Studium/assets/1070669/c1902ed1-3e26-4a22-aeaf-e1b39de3c616">

**Comment by xwolfde** [comment]
Zugang fehlt. 

sollte die Reihenfolge der erwiterten Filter auch geändert werden?

**Comment by wrcg** [comment]
![image](https://github.com/RRZE-Webteam/FAU-Studium/assets/9526974/53fe3e38-48af-451c-865c-f3a663726b8c)
Filterauswahl Eingeschränkt (NC) zeigt auch Studiengänge mit "Zulassungsfrei mit Eignungsfeststellungsverfahren an"?!

**Comment by wrcg** [comment]
![image](https://github.com/RRZE-Webteam/FAU-Studium/assets/9526974/91380893-c10f-46a0-89d4-1ab9d2188022)
 warum kann nicht nach den Zugangsvoraussetzungen vorgefiltert werden?
